apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.component_id}}
  namespace: dev-ns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ${{values.component_id}}
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
    spec:
      containers:
      - image: 192.168.112.245:5000/${{values.component_id}}:v0.0.1-3b6f140-20220927182011
        name: ${{values.component_id}}
        ports:
        - containerPort: 8080
