---
apiVersion: v1
kind: Service
metadata:
  name: ${{values.component_id}}
  namespace: dev-ns
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ${{values.component_id}}